name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-version: ['7.2', '7.4', '8.0']

    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@2.26.0
      with:
        php-version: ${{ matrix.php-version }}
        coverage: xdebug
        tools: phpunit
        extensions: simplexml, dom, xml, xdebug, intl

    - name: Install Dependencies
      run: |
        sudo composer self-update --no-interaction
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Execute PHPUnit tests
      run: vendor/bin/phpunit
